name: Hello World

on:
  push:
    branches: [main]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@2
    - name: Say Hello World
      run: echo "Hello, World!"
